### PR TITLE
Make property tests work again

### PR DESCRIPTION
**Pull request by MansurAshraf**
Tests were not running before. This change ensure tests are running (but not necessarily passing ...yet)

### CODE REVIEW

**Comment by johnynek** [comment]
Looks good to me, but question: how can we be sure the tests are all running now? Can we set scalatest to error if you have a property that never asserts?

**Comment by MansurAshraf** [comment]
I inverted the assert conditions in BaseProperties and made sure that tests run and fail.

**Comment by johnynek** [comment]
@MansurAshraf cool. Can you comment on what the PR in #197 should do to be compatible with this style?

**Comment by johnynek** [comment]
The URL injection test failed. It is flakey. Can you switch it from using the default `Arbitrary.arbitrary[String]: Gen[String]` to something like:

```scala
Arbitrary.arbitrary[String].filter(s => Try(new Url(s)).isSuccess)
```
then we only start with strings that won't throw.

**Comment by johnynek** [comment]
Thanks for doing this! Next stop: code coverage.

**Pull request merged**
