### PR TITLE
Build bijection-scrooge for scala 2.11

### PR DESCRIPTION
**Pull request by colinmarc**
I was able to build without any issues.

(sorry for the duplicate PR. I messed up at my githubbing somehow.)

### CODE REVIEW

**Comment by ianoc** [comment]
Looks like tests are failing here in both builds

**Comment by johnynek** [comment]
@colinmarc doesn't compile, yo! Can I talk you into a minor fix?

**Comment by colinmarc** [comment]
Ha, yes, sorry.

**Comment by colinmarc** [comment]
All better! Not sure why they were passing locally for me before...

**Pull request merged**
